### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by zhajiahe** [phoenixdyf/-#1]
作者你好，很激动发现了你在做这方面的工作，我是从事大模型算法工作的，最近刚刚从事设备运维相关项目，想向你请教两个问题：
1. 计算这些统计特征如何选择合适的计算区间（windows)，是否有设置阈值的经验
2. 由于设备工况比较复杂，如何消除工况不同带来的影响

**Comment by phoenixdyf** [comment]
1. 针对多维传感器数据的统计特征，设计阈值十分困难。面向大规模应用会出现频繁误报情况。可以参考国际标准对关键指标进行设计。
2. 非平稳工况一直是业界痛点，这方面各自企业会有针对性的解决方案，如消除非平稳工况影响、工况稳定性分段、高级信号处理、统计分析结合AI等。
如果有兴趣交流，可以发我邮箱详细沟通。

**Comment by zhajiahe** [comment]
> 1. 针对多维传感器数据的统计特征，设计阈值十分困难。面向大规模应用会出现频繁误报情况。可以参考国际标准对关键指标进行设计。
> 2. 非平稳工况一直是业界痛点，这方面各自企业会有针对性的解决方案，如消除非平稳工况影响、工况稳定性分段、高级信号处理、统计分析结合AI等。
>    如果有兴趣交流，可以发我邮箱详细沟通。

感谢回复！
